require:
  - rubocop/rspec
  - rubocop/rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
