require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*.jbuilder'
